apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-helloworld
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-helloworld
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kustomize-helloworld
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
