apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-ui
spec:
  revisionHistoryLimit: 6
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: helloworld-ui
  template:
    metadata:
      labels:
        app: helloworld-ui
    spec:
      containers:
        - name: guestbook-ui
          image: docker.io/jelledruyts/inspectorgadget:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
