apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-ui
spec:
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: helloworld-ui
  template:
    metadata:
      labels:
        app: helloworld-ui
    spec:
      containers:
        - name: guestbook-ui
          image: gcr.io/google-samples/gb-frontend:sample-public-image-v5-5be2e51
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
